Add BioCatch session ID Header
frollous/frollo-swift-sdk pull request #137
Opened 2021-07-29 03:17 UTC by sincychacko-frollo

[SDK-659]

2021-07-29 03:22 UTC, nickfrollo requested changes

2021-07-29 03:22 UTC, nickfrollo commented on Sources/FrolloSDK/Network/Network.swift
> +    internal init(serverEndpoint: URL, authentication: Authentication, encoder: JSONEncoder? = nil, pinnedPublicKeys: [URL: [SecKey]]? = nil, customerSessionID: String? = nil) {
Initialising the session ID here means it can't change during the lifetime of the app. If the user logs out then it won't change as it needs to. We should delegate it out like the token so it's always supplied by the host app

2021-07-29 03:22 UTC, nickfrollo commented on Sources/FrolloSDK/FrolloSDKConfiguration.swift
> +    internal let customerSessionID: String?
Can we rename to a more generic "sessionID" please?

2021-07-29 03:25 UTC, sincychacko-frollo commented on Sources/FrolloSDK/Network/Network.swift
> +    internal init(serverEndpoint: URL, authentication: Authentication, encoder: JSONEncoder? = nil, pinnedPublicKeys: [URL: [SecKey]]? = nil, customerSessionID: String? = nil) {
Right. 👍 I'll make the change.

2021-07-29 03:53 UTC, dipeshfrollo approved these changes

2021-07-29 03:54 UTC, hailefrollo approved these changes

2021-07-29 08:09 UTC, sincychacko-frollo commented on Sources/FrolloSDK/Network/Network.swift
> +    internal init(serverEndpoint: URL, authentication: Authentication, encoder: JSONEncoder? = nil, pinnedPublicKeys: [URL: [SecKey]]? = nil, customerSessionID: String? = nil) {
@nickfrollo I added a DataSource for the host app to provide sessionID. But there was no common place to add the header, so had to modify individual service requests to include the header.

2021-07-29 22:55 UTC, nickfrollo approved these changes
Looks good, nice work!

Would it be worth centralising the calls to self.network.sessionManager.request() so the headers can all be added in the same place? (I realise this commit would still mean touching all calls that exist currently). Might not work if you're deliberately excluding some calls though (I've not checked 🙂)

2021-07-30 03:05 UTC, sincychacko-frollo commented
> Looks good, nice work!
> 
> Would it be worth centralising the calls to self.network.sessionManager.request() so the headers can all be added in the same place? (I realise this commit would still mean touching all calls that exist currently). Might not work if you're deliberately excluding some calls though (I've not checked 🙂)

@nickfrollo Updated the PR.

2021-08-24 01:37 UTC, nickfrollo approved these changes

2021-08-24 01:44 UTC, merged