WA-2770 add apple wallet support
frollous/frollo-swift-sdk pull request #176
Opened 2022-01-04 00:22 UTC by NeilCossorFrollo

https://frollo.atlassian.net/browse/WA-2770
updates to Get cards, plus query enrolment status, and actually enrol.. starting point here
https://dev.frollo.com.au/docs/frollo-api/branches/feature%2Fdigital-wallet-enrolment/b3A6MzI2ODIzMjQ-get-card-enrolment-status

Checklist
Use the ✅ emoji for when it's been done; ⛔ when it still needs work; strikethrough when an item of the checklist does not apply to the changes.

- Is the destination branch correct & intended? ✅
- Is the correct JIRA ticket referenced? ✅
- Is the correct API docs/Confluence Page referenced? ✅
- Have all the AC's in the ticket passed? ✅
- Have you followed proper naming conventions in the code? ✅
- Has the code been properly covered with unit tests? ✅
- Have you regenerated the mock DBs, if the datamodel was modified ✅
- Have you added migration tests (if applicable)? ✅
- Have the unit tests passed locally (if applicable)? ✅
- Have you addressed the code warnings if any? ✅
- Have you tested the API and made sure the documentation is up-to-date? APIs not outside Cont, where we have no cards
- Have you added documentation for all public methods & types ✅

2022-01-04 05:37 UTC, dipeshfrollo requested changes
Great Job Neil. Nice documentation.

I believe the new APIs / changes are in v2.17? If thats the case then can you please update the APIVersion in SDK and update tests accordingly?

2022-01-04 05:37 UTC, dipeshfrollo commented on Sources/FrolloSDK/Cards/Cards.swift
> +        // FIXME: NC hack to pretend we got the OTP required flavour
Forgot to remove comments?

2022-01-04 06:43 UTC, NeilCossorFrollo commented on Sources/FrolloSDK/Cards/Cards.swift
> +        // FIXME: NC hack to pretend we got the OTP required flavour
No. If we need to manually force OTP flavour to test popups in app, then temporary uncomment it.

2022-01-04 06:45 UTC, dipeshdhakal commented on Sources/FrolloSDK/Cards/Cards.swift
> +        // FIXME: NC hack to pretend we got the OTP required flavour
OK, as long as we dont forget to remove this before release. Otherwise we can achieve this using charles too.

2022-01-07 00:59 UTC, hailefrollo approved these changes

2022-01-07 01:00 UTC, hailefrollo commented
@NeilCossorFrollo 👍 very detail!

2022-01-07 01:22 UTC, merged