Feature/sdk-708_update_cdr_config_APIs
frollous/frollo-swift-sdk pull request #182
Opened 2022-02-04 03:34 UTC by NeilCossorFrollo

https://frollo.atlassian.net/browse/SDK-708
Links to API docs in that ticket.
Note there are a number of mandatory new fields, including one defined in 2.15 which was missing. To get database migration tests working, needed to add defaults in xcdatamodel which will be stamped over on config/cdr refresh.
Unit tests for a bunch of decode failures implemented using simple string substitution. Not perfect where same "key" is in different levels of nested JSON subfields e.g. "id" or "name"
Note at time of this PR, the backend ticket is NOT in place, so purely relies on JSON manually generated from blend of real response data, and documented sample data in beta API docs.

Checklist
Use the ✅ emoji for when it's been done; ⛔ when it still needs work; strikethrough when an item of the checklist does not apply to the changes.

- Is the destination branch correct & intended? ✅ 
- Is the correct JIRA ticket referenced? ✅ 
- Is the correct API docs/Confluence Page referenced? ✅ 
- Have all the AC's in the ticket passed? ✅ 
- Have you followed proper naming conventions in the code? ✅ 
- Has the code been properly covered with unit tests? ✅ (not 100% for failure cases, better than was there)
- Have you regenerated the mock DBs, if the datamodel was modified ✅ 
~~Have you added migration tests (if applicable)?~~ N/A (same 1.7.8)
- Have the unit tests passed locally (if applicable)? ✅ 
- Have you addressed the code warnings if any? ✅ 
- Have you tested the API and made sure the documentation is up-to-date? ✅ Given API docs are beta, not implemented yet
- Have you added documentation for all public methods & types ✅

2022-02-07 06:06 UTC, dipeshfrollo requested changes

2022-02-07 06:06 UTC, dipeshfrollo commented on Tests/Resources/API/CDR/get_cdrConfiguration_2RP.json
> +    "id": "2",
Isnt ID supposed to be an Int64?

2022-02-07 06:06 UTC, dipeshfrollo commented on Sources/FrolloSDK/Model/API/CDR/APICDRConfigurationResponse.swift
> +        case cdrPolicyURL = "cdr_policy_url"
I think we will also need a required field "id"

2022-02-08 04:04 UTC, NeilCossorFrollo commented on Tests/Resources/API/CDR/get_cdrConfiguration_2RP.json
> +    "id": "2",
With some of the IDs as string and some as integer (and not knowing who is allocating a specific ID), I missed that the 2.17 docs say this is Integer, so updating to Int64.

2022-02-08 04:05 UTC, NeilCossorFrollo commented on Sources/FrolloSDK/Model/API/CDR/APICDRConfigurationResponse.swift
> +        case cdrPolicyURL = "cdr_policy_url"
it is there, with coding key from id to configID

2022-02-08 04:23 UTC, hailefrollo commented on Sources/FrolloSDK/Model/API/CDR/APICDRConfigurationResponse.swift
> +        case cdrPolicyURL = "cdr_policy_url"
I notice the `id` now BE return the number, not string. 🤷‍♂️

2022-02-09 04:27 UTC, NeilCossorFrollo commented
Updated with different endpoint, so get now required externalID as parameter, which ripples up the chain thru Link and app (externalID generated from tenant)

2022-02-09 04:41 UTC, dipeshfrollo approved these changes
Looks good. Just 2 minor comments.

2022-02-09 04:41 UTC, dipeshfrollo commented on Sources/FrolloSDK/Aggregation/Aggregation.swift
> +    public func refreshCDRConfiguration(externalID: String,
Can we add new parameter in documentation please?

2022-02-09 04:41 UTC, dipeshfrollo commented on Tests/Database/DatabaseMigrationTests.swift
> +    func testGenerateTestCoreDataDatabases() {
Lets not forget to comment this

2022-02-09 05:40 UTC, NeilCossorFrollo commented on Tests/Database/DatabaseMigrationTests.swift
> +    func testGenerateTestCoreDataDatabases() {
fixed in last commit

2022-02-09 05:40 UTC, NeilCossorFrollo commented on Sources/FrolloSDK/Aggregation/Aggregation.swift
> +    public func refreshCDRConfiguration(externalID: String,
added comment for new param

2022-02-09 05:40 UTC, merged