WA-3497: remove API cache in all WA
frollous/frollo-swift-sdk pull request #212
Opened 2022-05-11 04:45 UTC by hailefrollo

2022-05-11 04:48 UTC, nickfrollo requested changes
@hailefrollo I'm not sure this quite meets the requirements of the ticket 🙂

We should be able to set a URL cache that is memory only rather than disabling entirely

2022-05-11 07:37 UTC, NeilCossorFrollo reviewed
unless I am crazy, that is 200MB which is a LOT of memory cache
I think (regardless) of new caching being change by this code, to clean up for whatever is already in cache, there should also be a call to purge the existing cache
URLCache.shared.removeAllCachedResponses()
so another pentest doesn't pick up leftovers from before the config change

2022-05-11 07:42 UTC, hailefrollo commented
@NeilCossorFrollo I tested when the app startup, it triggered reset() function which call `removeAllCachedResponses`. So when pentest start open the app, it will clear previous cache.

2022-05-12 01:03 UTC, NeilCossorFrollo approved these changes

2022-05-12 04:57 UTC, merged