[SDK-493] Payment Pay anyone
frollous/frollo-swift-sdk pull request #25
Opened 2020-10-08 03:38 UTC by dipeshfrollo

[SDK-493]

2020-10-08 03:40 UTC, MaherKSantina approved these changes

2020-10-08 04:01 UTC, sincychacko-frollo approved these changes

2020-10-08 22:47 UTC, nickfrollo requested changes
Great job!

We may wish to cache Payment response as in the future there will be a way to fetch scheduled payments. I wouldn't worry about this for now though.

2020-10-08 22:47 UTC, nickfrollo commented on Sources/Model/API/Payments/APIPayAnyoneRequest.swift
> +    let sourceAccountId: Int64
Can we capitalise ID for consistency with the rest of the project?

2020-10-08 22:48 UTC, dipeshfrollo commented on Sources/Model/API/Payments/APIPayAnyoneRequest.swift
> +    let sourceAccountId: Int64
Will update. Thanks

2020-10-08 22:51 UTC, dipeshfrollo commented
@nickfrollo yes we will do the caching when we implement GET /payments. BTW responses of /payments/bpay, /payments/payanyone and /payments/transfer are different so each will have different models (uncached)

2020-10-08 22:59 UTC, MaherKSantina commented
So I guess we have 2 choices to cache the data:
1. Do it similar to messages where there is a table for each type and a main one
2. Cache everything in one table and have a different class for each type, and when we fetch the payments from the table we map the fields to the corresponding type

Personally I prefer option 2 because it doesn't require multiple tables in the database and we can get the data from one place

2020-10-08 23:05 UTC, dipeshfrollo commented
3. Only cache for GET /payments 😄  . Why should we cache these responses anyway?

2020-10-08 23:08 UTC, MaherKSantina commented
haha right! I'm happy with that

2020-10-09 04:41 UTC, nickfrollo approved these changes

2020-10-09 04:43 UTC, merged