XCode 12 fixes
frollous/frollo-swift-sdk pull request #35
Opened 2020-10-26 21:58 UTC by MaherKSantina

- Added tmp.xcconfig which has the configuration to make carthage update command work on XCode 12

## Note
Command `fastlane ios update_dependencies` and `fastlane ios bootstrap` will not work unless you run this command in the terminal first
```
export XCODE_XCCONFIG_FILE=$PWD/tmp.xcconfig
```

I've already configured this in CircleCI so it should work in theory, but I'm going to create this PR to see if the build fails or not

2020-10-28 04:25 UTC, nickfrollo requested changes
Good job! Just a couple of tweaks

2020-10-28 04:25 UTC, nickfrollo commented on .circleci/config.yml
>      shell: /bin/bash --login -o pipefail
Please remove this line, it caused problems in other projects

2020-10-28 04:25 UTC, nickfrollo commented on .circleci/config.yml
> +          command: xcrun simctl create 'iPhone SE (14.0)' com.apple.CoreSimulator.SimDeviceType.iPhone-SE com.apple.CoreSimulator.SimRuntime.iOS-14-0
Can we get a 13.5 sim running? Even if different device

2020-10-28 04:26 UTC, MaherKSantina commented on .circleci/config.yml
> +          command: xcrun simctl create 'iPhone SE (14.0)' com.apple.CoreSimulator.SimDeviceType.iPhone-SE com.apple.CoreSimulator.SimRuntime.iOS-14-0
Sure thing I'll look for one

2020-10-28 04:26 UTC, MaherKSantina commented on .circleci/config.yml
>      shell: /bin/bash --login -o pipefail
Sure thing

2020-10-29 05:14 UTC, nickfrollo requested changes
Just one tweak on the tests please! Looking good otherwise!

2020-10-29 05:14 UTC, nickfrollo commented on Tests/Network/NetworkAuthenticatorTests.swift
> +        wait(for: [expectation1, expectation2, expectation3], timeout: 300.0)
5 minutes? Not sure we should wait that long. Instead I'd remove one of the network calls. I'd guess what happens is the 3rd one sometimes fires too late to get cancelled.

2020-10-29 21:39 UTC, nickfrollo approved these changes

2020-11-06 02:32 UTC, sincychacko-frollo approved these changes

2020-11-06 02:41 UTC, merged