[SDK-460] Remove tracking_type from create budget
frollous/frollo-swift-sdk pull request #43
Opened 2020-11-20 01:02 UTC by dipeshfrollo

[SDK-460] Remove tracking_type from create budget

2020-11-20 01:29 UTC, sincychacko-frollo approved these changes

2020-11-20 02:33 UTC, nickfrollo requested changes
Just check on the docs in comments please

2020-11-20 02:33 UTC, nickfrollo commented on Sources/Budgets/Budgets.swift
> -                                    trackingType: Budget.TrackingType,
Don't forget to remove the parameter from the documentation :)

2020-11-20 02:41 UTC, dipeshfrollo commented on Sources/Budgets/Budgets.swift
> -                                    trackingType: Budget.TrackingType,
Updated. Thanks 😊

2020-11-22 22:11 UTC, nickfrollo approved these changes
Thanks!

2020-11-22 22:16 UTC, merged