Adjust to API changes for KYC model
frollous/frollo-swift-sdk pull request #69
Opened 2021-02-16 23:54 UTC by dipeshfrollo

2021-02-17 00:02 UTC, sincychacko-frollo approved these changes

2021-02-18 21:38 UTC, nickfrollo requested changes
Looks good to me! Just one possible issue, mainly just some comments around docs

2021-02-18 21:38 UTC, nickfrollo commented on Sources/Model/Transient/UserKYC.swift
> +        /// Unique ID of the dosument. Generated by backend.
Typo

2021-02-18 21:38 UTC, nickfrollo commented on Sources/Model/Transient/UserKYC.swift
>          /// Country of the document
What format? AU or Australia or AUS?

2021-02-18 21:38 UTC, nickfrollo commented on Sources/Model/Transient/UserKYC.swift
> +        /// Array of `ExtraData`
Any details what goes in this? 🙂

2021-02-18 21:38 UTC, nickfrollo commented on Sources/Model/Transient/UserKYC.swift
> +        public init(documentID: String? = nil, country: String? = nil, idExpiry: String? = nil, idNumber: String, idSubType: String? = nil, idType: IDType, region: String? = nil, extraData: [ExtraDat
I don't see documentID stored anywhere in the initialiser - I assume it should be?

2021-02-18 21:38 UTC, nickfrollo commented on Sources/Model/Transient/UserKYC.swift
> +            /// Type of the `ExtraData`. Used to describe the contents of KVP Data
What's KVP mean here?

2021-02-18 21:38 UTC, nickfrollo commented on Tests/KYC/KYCTests.swift
> +                    XCTAssertEqual(userKYC.email, "drsheldon@frollo.us")
😆

2021-02-18 23:54 UTC, nickfrollo approved these changes
Great job

2021-02-19 00:03 UTC, merged